
const Images = {
  splash_img: require('./images/splash_img.png'),
  recipe:  require('./images/recipe.jpg'),
  tutorial:  require('./images/tutorial.png'),
  flour:  require('./images/flour.png'),
  cooking:  require('./images/cooking.png'),
  mixing:  require('./images/mixing.png'),
  chef:  require('./images/chef.png'),
  eye:  require('./images/eye.png'),
  google:  require('./images/google.png'),
  facebook:  require('./images/facebook.png'),
  top:  require('./images/top.png'),
  search:  require('./images/search.png'),
  breakfast:  require('./images/breakfast.png'),
  brunch:  require('./images/brunch.png'),
  lunch:  require('./images/lunch.png'),
  dinner:  require('./images/dinner.png'),
  tea:  require('./images/tea.png'),
  snack:  require('./images/snack.png'),
  star :  require('./images/star.png'),
  pizza :  require('./images/pizza.jpg'),
  Biangbiang:require('./images/Biangbiang.jpg'),
  samosa:require('./images/samosa.jpg'),
  rice: require('./images/rice.jpg'),
  noodle: require('./images/noodle.jpg'),
  spring: require('./images/spring.jpg'),
  ranveer:  require('./images/ranveer.png'),
  sanjeev: require('./images/sanjeev.png'),
  gordan : require('./images/gordan.png'),
  vikas : require('./images/vikas.png'),
  alian: require('./images/alian.png'),
  jamie: require('./images/jamie.png'),
  timer: require('./images/timer.png'),
  left: require('./images/left.png'),
  inactive:require('./images/Inactive.png'),
  active:require('./images/active.png'),
  chefpic:  require('./images/chefpic.png'),
  location:  require('./images/location.png'),
  notification:require('./images/notification.png'),
  home: require('./images/home.png'),
  profile:require('./images/profile.png'),
  navBar: require('./images/BarMenu.png'),
  save: require('./images/save.png'),
  vector: require('./images/Vector.png'),
  notify:require('./images/Notify.png'),
  saveActive: require('./images/saveActive.png'),
  profileActive:require('./images/profileActive.png'),
  options: require('./images/options.png'),
  stars: require('./images/stars.png'),
  share:require('./images/share.png'),
  message:require('./images/message.png'),
  unsave:require('./images/unsave.png'),
  lefts: require('./images/lefts.png'),
  searchs:  require('./images/search.png'),
  filter: require('./images/filter.png'),
  more: require('./images/more.png'),
  dp: require('./images/dp.png'),
};

export {Images};
